platform :ios, '7.0'

target 'LWMTA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LWMTA
  
  pod 'LWMTA', :path => '../'
  

end
